framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        enabled: true
        cookie_lifetime: 0
        cookie_secure: false
        cookie_samesite: lax
        gc_probability: 0
        gc_maxlifetime: 300

    #esi: true
    #fragments: true
    php_errors:
        log: true
